openapi: 3.0.3
info:
  title: Simple Food API - Dishes
  version: 0.1.0-draft
  description: Dish entities specification
servers: []
paths:
  /dishes:
    get:
      operationId: listDishes
      summary: List dishes
      tags: [Dishes]
      responses:
        '200':
          description: List of dishes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dish'
    post:
      operationId: createDish
      summary: Create dish
      tags: [Dishes]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dish'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dish'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './spec-simple-food-common.yaml#/components/schemas/Error'
  /dishes/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/DishId'
    get:
      operationId: getDishById
      summary: Get dish by id
      tags: [Dishes]
      responses:
        '200':
          description: Dish
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dish'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './spec-simple-food-common.yaml#/components/schemas/Error'
    put:
      operationId: updateDish
      summary: Replace dish
      tags: [Dishes]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dish'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dish'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './spec-simple-food-common.yaml#/components/schemas/Error'
    delete:
      operationId: deleteDish
      summary: Delete dish
      tags: [Dishes]
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: './spec-simple-food-common.yaml#/components/schemas/Error'
  /dishes/search:
    post:
      operationId: searchDishes
      summary: Search dishes
      tags: [Dishes]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DishSearchRequest'
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dish'
components:
  schemas:
    DishId:
      type: string
      format: uuid

    DishSearchRequest:
      type: object
      description: Search criteria for dishes
      properties:
        query:
          type: string
          description: Free-text query over title, categories and recipes
      required: [query]

    Dish:
      type: object
      description: Dish composed of products and recipes
      properties:
        id:
          $ref: '#/components/schemas/DishId'
        title:
          type: string
        calories:
          $ref: './spec-simple-food-common.yaml#/components/schemas/NutritionalValue'
        proteins:
          $ref: './spec-simple-food-common.yaml#/components/schemas/NutritionalValue'
        fats:
          $ref: './spec-simple-food-common.yaml#/components/schemas/NutritionalValue'
        carbohydrates:
          $ref: './spec-simple-food-common.yaml#/components/schemas/NutritionalValue'
        weight:
          $ref: './spec-simple-food-common.yaml#/components/schemas/Weight'
        author:
          $ref: './spec-simple-food-common.yaml#/components/schemas/Author'
        categories:
          type: array
          items:
            type: string
        recipes:
          type: array
          description: Preparation steps
          items:
            type: string
        products:
          type: array
          description: Products used in the dish with portions
          items:
            $ref: '#/components/schemas/ProductPortion'
      required: [id, title, calories, proteins, fats, carbohydrates, weight]

    ProductPortion:
      type: object
      description: Reference to a product with portion information
      properties:
        productId:
          $ref: './spec-simple-food-api-products.yaml#/components/schemas/ProductId'
        weight:
          $ref: './spec-simple-food-common.yaml#/components/schemas/Weight'
      required: [productId, weight]


